version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    deploy:
      placement:
        constraints: [node.hostname == oracle]
    ports:
      - "3000:3000"
    volumes:
      - /mnt/user/freshdata/monitoring/grafana:/var/lib/grafana
    restart: always

  prometheus:
    image: prom/prometheus:latest
    deploy:
      placement:
        constraints: [node.hostname == oracle]
    ports:
      - "9090:9090"
    volumes:
      - /mnt/user/freshdata/monitoring/prometheus:/etc/prometheus
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    deploy:
      placement:
        constraints: [node.hostname == oracle]
    ports:
      - "3001:3001"
    volumes:
      - /mnt/user/freshdata/monitoring/uptime-kuma:/app/data
    restart: always

  loki:
    image: grafana/loki:latest
    deploy:
      placement:
        constraints: [node.hostname == oracle]
    ports:
      - "3100:3100"
    volumes:
      - /mnt/user/freshdata/monitoring/loki:/etc/loki
    restart: always

  speedtest-tower:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    deploy:
      placement:
        constraints: [node.hostname == swarm-manager]
    ports:
      - "8765:80"
    volumes:
      - /mnt/user/freshdata/monitoring/speedtest-tracker-tower:/config
    restart: always

  speedtest-i38100:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    deploy:
      placement:
        constraints: [node.hostname == docker-desktop]
    ports:
      - "8766:80"
    volumes:
      - /mnt/user/freshdata/monitoring/speedtest-tracker-i38100:/config
    restart: always

  speedtest-oracle:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    deploy:
      placement:
        constraints: [node.hostname == oracle]
    ports:
      - "8767:80"
    volumes:
      - /mnt/user/freshdata/monitoring/speedtest-tracker-oracle:/config
    restart: always
