version: "3.8"

services:

  watchtower-i38100:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=43200  # Every 12 hours (43200 seconds)
    deploy:
      placement:
        constraints:
          - node.labels.name == i38100

  watchtower-oracle:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=43200
    deploy:
      placement:
        constraints:
          - node.labels.name == oracle-prime
