version: "3.8"

services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
        - TUNNEL_TOKEN=eyJhIjoiMDQ1MDllY2Q0YTAyOTBhYjI1NGJkZDE2Y2E5M2QxYWQiLCJ0IjoiMzI4NjcxODYtOGM2Mi00ZDYzLTljZDItZDY2MTc0MzViMjM5IiwicyI6Ik1qRTBNRGN6TTJFdE9UQmhOaTAwWVRKbExXSmhNell0TTJNNE9UQTRZMlkwTXpRMyJ9
=
plex:
    image: ghcr.io/binhex/arch-plex
    ports:
      - "32400:32400"
    volumes:
      - /mnt/user/tv:/tv
      - /mnt/user/tv4k:/tv4k
      - /mnt/user/media/YouTube:/YouTube
      - /mnt/user/movies:/movies
      - /mnt/user/freshdata/media/plex:/config
    deploy:
      placement:
        constraints:
          - node.labels.name == unraid

  jellyfin:
    image: ghcr.io/binhex/arch-jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /mnt/user/aniz/Backup/nymph:/media
      - /mnt/user/freshdata/media/jellyfin:/config
    deploy:
      placement:
        constraints:
          - node.labels.name == unraid

  radarr:
    image: ghcr.io/binhex/arch-radarr
    ports:
      - "7878:7878"
    volumes:
      - /mnt/user/freshdata/media/radarr:/config
      - /mnt/user/downloads:/downloads
      - /mnt/user/incomplete:/incomplete
      - /mnt/user/movies:/media


  radarr4k:
    image: ghcr.io/binhex/arch-radarr
    ports:
      - "17878:7878"
    volumes:
      - /mnt/user/freshdata/media/radarr4k:/config
      - /mnt/user/downloads:/downloads
      - /mnt/user/incomplete:/incomplete
      - /mnt/user/movies:/media

  sonarr:
    image: ghcr.io/binhex/arch-sonarr
    ports:
      - "8989:8989"
    volumes:
      - /mnt/user/freshdata/media/sonarr:/config
      - /mnt/user/downloads:/downloads
      - /mnt/user/incomplete:/incomplete
      - /mnt/user/tv:/series
      - /mnt/user/tv4k:/tv4k:rw

  whisparr:
    image: ghcr.io/hotio/whisparr
    ports:
      - "6969:6969"
    volumes:
      - /mnt/user/freshdata/media/whisparr:/config
      - /mnt/user/downloads:/downloads
      - /mnt/user/incomplete:/incomplete
      - /mnt/user/aniz/Backup/nymph:/media


  prowlarr:
    image: ghcr.io/binhex/arch-prowlarr
    ports:
      - "9696:9696"
    volumes:
      - /mnt/user/freshdata/media/prowlarr:/config


  sabnzbd:
    image: ghcr.io/binhex/arch-sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - /mnt/user/freshdata/media/sabnzbd:/config
      - /mnt/user/downloads:/downloads
      - /mnt/user/incomplete:/incomplete
    deploy:
      placement:
        constraints:
          - node.labels.name == unraid
